import {
  siRust,
  siPython,
  siTypescript,
  siJavascript,
  siReact,
  siVuedotjs,
  siAngular,
  siNodedotjs,
  siDocker,
  siPostgresql,
  siMysql,
  siMongodb,
  siRedis,
  siKubernetes,
  siGit,
  siLinux,
  siGooglecloud,
  siGraphql,
  siGo,
  siSwift,
  siKotlin,
  siCplusplus,
  siC,
  siRuby,
  siPhp,
  siScala,
  siElixir,
  siHaskell,
  siNextdotjs,
  siSvelte,
  siTailwindcss,
  siWebpack,
  siFigma,
  siSketch,
  siGithub,
  siGitlab,
  siDjango,
  siFlask,
  siSpring,
  siLaravel,
  siRubyonrails,
  siExpress,
  siFirebase,
  siSupabase,
  siPrisma,
  siVite,
  siVitest,
  siJest,
  siStorybook,
  siWebassembly,
  siTerraform,
  siAnsible,
  siJenkins,
  siGithubactions,
  siNginx,
  siApache,
  siElasticsearch,
  siSqlite,
  siCss,
  siHtml5,
  siBun,
  siDeno,
  siNuxt,
  siSass,
  siLess,
} from 'simple-icons';
import {
  ClipboardList,
  Paintbrush2,
  BarChart2,
  Globe,
  Users,
  Wrench,
  Shield,
  Layers,
  Smartphone,
  Terminal,
  Database,
  Cloud,
  Cpu,
  Brain,
  LineChart,
  TestTube2,
  type LucideIcon,
} from 'lucide-react';

interface SimpleIconDef {
  path: string;
  title: string;
  hex: string;
}

type SkillIconEntry =
  | { type: 'simple'; icon: SimpleIconDef }
  | { type: 'lucide'; icon: LucideIcon };

// Normalise a skill string for lookup: lowercase, strip spaces/dots/dashes
function normalise(s: string): string {
  return s.toLowerCase().replace(/[\s.\-_+#]/g, '');
}

const simpleIconMap: Record<string, SimpleIconDef> = {
  rust: siRust,
  python: siPython,
  typescript: siTypescript,
  javascript: siJavascript,
  js: siJavascript,
  ts: siTypescript,
  react: siReact,
  'reactjs': siReact,
  vuejs: siVuedotjs,
  vue: siVuedotjs,
  angular: siAngular,
  nodejs: siNodedotjs,
  node: siNodedotjs,
  docker: siDocker,
  postgresql: siPostgresql,
  postgres: siPostgresql,
  mysql: siMysql,
  mongodb: siMongodb,
  mongo: siMongodb,
  redis: siRedis,
  kubernetes: siKubernetes,
  k8s: siKubernetes,
  git: siGit,
  linux: siLinux,
  googlecloud: siGooglecloud,
  gcp: siGooglecloud,
  graphql: siGraphql,
  go: siGo,
  golang: siGo,
  swift: siSwift,
  kotlin: siKotlin,
  'c': siC,
  'c++': siCplusplus,
  cpp: siCplusplus,
  ruby: siRuby,
  php: siPhp,
  scala: siScala,
  elixir: siElixir,
  haskell: siHaskell,
  nextjs: siNextdotjs,
  svelte: siSvelte,
  tailwindcss: siTailwindcss,
  tailwind: siTailwindcss,
  webpack: siWebpack,
  figma: siFigma,
  sketch: siSketch,
  github: siGithub,
  gitlab: siGitlab,
  django: siDjango,
  flask: siFlask,
  spring: siSpring,
  springboot: siSpring,
  laravel: siLaravel,
  rails: siRubyonrails,
  rubyonrails: siRubyonrails,
  express: siExpress,
  expressjs: siExpress,
  firebase: siFirebase,
  supabase: siSupabase,
  prisma: siPrisma,
  vite: siVite,
  vitest: siVitest,
  jest: siJest,
  storybook: siStorybook,
  webassembly: siWebassembly,
  wasm: siWebassembly,
  terraform: siTerraform,
  ansible: siAnsible,
  jenkins: siJenkins,
  githubactions: siGithubactions,
  nginx: siNginx,
  apache: siApache,
  elasticsearch: siElasticsearch,
  sqlite: siSqlite,
  css: siCss,
  css3: siCss,
  html: siHtml5,
  html5: siHtml5,
  bun: siBun,
  deno: siDeno,
  nuxt: siNuxt,
  nuxtjs: siNuxt,
  sass: siSass,
  scss: siSass,
  less: siLess,
};

const lucideIconMap: Record<string, LucideIcon> = {
  projectmanagement: ClipboardList,
  agile: ClipboardList,
  scrum: ClipboardList,
  kanban: ClipboardList,
  productmanagement: ClipboardList,
  uidesign: Paintbrush2,
  uxdesign: Paintbrush2,
  uiux: Paintbrush2,
  design: Paintbrush2,
  webdesign: Paintbrush2,
  productdesign: Paintbrush2,
  analytics: BarChart2,
  dataanalysis: BarChart2,
  businessintelligence: BarChart2,
  bi: BarChart2,
  seo: Globe,
  webdevelopment: Globe,
  internationalization: Globe,
  i18n: Globe,
  teamlead: Users,
  teamleadership: Users,
  leadership: Users,
  mentoring: Users,
  management: Users,
  devops: Wrench,
  sre: Wrench,
  cicd: Wrench,
  cybersecurity: Shield,
  security: Shield,
  infosec: Shield,
  appsec: Shield,
  architecture: Layers,
  systemdesign: Layers,
  microservices: Layers,
  mobile: Smartphone,
  mobiledev: Smartphone,
  ios: Smartphone,
  android: Smartphone,
  cli: Terminal,
  shell: Terminal,
  bash: Terminal,
  scripting: Terminal,
  dba: Database,
  databases: Database,
  sql: Database,
  cloudcomputing: Cloud,
  cloud: Cloud,
  embeddedsystems: Cpu,
  embedded: Cpu,
  firmware: Cpu,
  iot: Cpu,
  machinelearning: Brain,
  ml: Brain,
  ai: Brain,
  deeplearning: Brain,
  nlp: Brain,
  datascience: LineChart,
  'data science': LineChart,
  testing: TestTube2,
  qa: TestTube2,
  qualityassurance: TestTube2,
  tdd: TestTube2,
};

export function getSkillIcon(skill: string): SkillIconEntry | null {
  const key = normalise(skill);
  if (simpleIconMap[key]) {
    return { type: 'simple', icon: simpleIconMap[key] };
  }
  if (lucideIconMap[key]) {
    return { type: 'lucide', icon: lucideIconMap[key] };
  }
  return null;
}
